
const rawText = `
NOMBRES COLONIAS 
1. MERCEDES EUAN  MELITON SALAZAR 
2. SEYDI PECH DOLORES OTERO 
3. PILAR  SANTA ROSA 
4. ANA GONZALEZ SANTA ROSA 
5. ROSY VERDE  DOLORES OTERO 
6. LUCIA HAU VICENTE SOLIS 
7. ALICIA CAUICH ROBLE AGRICOLA 
8. CLEMENTINA VAZQUEZ SANTA ROSA  
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
 
 
NOMBRES COLONIAS 
9.         DAMARIS POOL CENTRO  
10. ISABEL EUAN  VICENTE SOLIS  
11. VANESSA COB MERCEDES BARRERA 
12. ROSY PALOMO CENTRO 
13. ROSA CETINA OBRERA 
14. VICTORIA AKE  SAMBULA 
15. ALEJANDRO SUNZA  MANZANA 115 
16. ISYEL LOZANO SERAPIO RENDON 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
 
 
NOMBRES COLONIAS 
17. MARGARITA CARDEÑA  42 SUR  
18. VERONICA 
MALDONADO 
MELITON SALAZAR 
19. PEDRO MARTINEZ CASTILLA CAMARA 
20. WENDY RAVELL MELITON SALAZAR 
21. MARTINA  DOLORES OTERO 
22. ANDREA SANCHEZ MERCEDES BARRERA 
23. MARICRUZ CELIS  MELITON SALAZAR 
24. MARIA SANCHEZ  CASTILLA CAMARA  
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
  
NOMBRES COLONIAS 
25. JAZMIN ORTIZ CECICLIO CHI 
26. FRANCIA  CASTILLA CAMARA 
27. BERTHA VELEZ  OBRERA 
28. VIVIANA MAY CASTILLA CAMARA 
29. MARIA CANTO  CASTILLA CAMARA 
30. SAMNATTHA DOLORES OTERO 
31. JUAN PECH MANZANA 115 
32. ESMERALDA SOLIS CASTILLA CAMARA 
33. ANA BRISEÑO CINCO COLONIAS 
 
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
 
NOMBRES COLONIAS 
34. LETICIA CASTRO  CASTILLA CAMARA 
35. MARIA JOSE  DOLORES OTERO 
36. MARISOL LAYNES  JARDINES SUR 
37. SILIA MARIN OBRERA 
38. ANAHI CENTRO 
39. JOSE CASTELLANOS DOLORES OTERO 
40. BEATRIZ PEREZ  MELITON SALAZAR 
41. EVERLINDA  AZCORRA  
42. MONSERRAT  OBRERA  
 
 
 
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
NOMBRES COLONIAS 
43. LIZET MACHORRO VILLA MAGNA 
44. DOÑA GABY CASTILLA CAMARA 
45. LETICIA  OBRERA 
46. REBECA PEREZ MANZANA 115 
47. ADDY YOLANDA  CASTILLA CAMARA  
48. ADRIANA CEBALLOS  CENTRO PEDRO INFANTE  
49. DANIEL GUZMAN  MELITON SALAZAR 
50. JOAQUIN CENTRO 
51. LIZETH PALACIOS  CASTILLA CAMARA  
52. NELLY  OBRERA 
53. ROSANA GOROCICA CENTRO 
 
 
 
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
  
NOMBRES COLONIAS 
54. CLAUDIA ARCILA CENTRO 
55. LIGIA AKE  CANTO  
56. ESTEFANY VALDEZ CINCO COLONIAS 
57. KATTY XOOL CENTRO 
58. SUGELY VERA MELITON SALAZAR 
59. CRISTIAN  OBRERA 
60. MARIEN PEREIRA OBRERA 
61. ANDY VALLE  MANZANA 115 
62. GABRIELA PERAZA  CENTRO HERMITA 
63. MARIBEL CASTILLO PEDRO INFANTE 
64. TERE CERVANTES CENTRO 
65. DELIA ALTAMIRANO DOLORES OTERO 
 
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
 
NOMBRES COLONIAS 
66. ALMA RODRIGUEZ MELITON SALAZAR 
67. ANA GONZALEZ SANTA ROSA 
68. SARA  MELITON SALAZAR 
69. GORETY  CASTILLA CAMARA 
70. ROSITA  MANZANA 115 
71. MERCEDES EUAN  MELITON SALAZAR 
72. LISET CELIS  CASTILLA CAMARA 
73. SELENE JIMENEZ 
DIAZ 
MERCEDES BARRERA 
74. DOÑA GLADYS  CASTILLA CAMARA  
75. ROSA ISELA  MERCEDES BARRERA  
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
 
NOMBRES COLONIAS 
76. ROSY SANCHEZ CENTRO 
77. LEYDI VAZQUEZ  MELITON SALAZAR 
78. KARINA MARTIN DELIO MORENO 
79. MONSE AGUILAR  CINCO COLONIAS 
80. TETE ITZA  CEMENTERIO GENERAL 
81. JOEL PALMA  CASTILLA CAMARA 
82. FATIMA DAZA MERCEDES BARRERA 
83. GABRIELA DEL 
SOCORRO CAAMAL 
CASTILLA CAMARA 
84. ELIZABETH PEREZ CENTRO  
85. SANDRA OXTE  OBRERA 
86. GABRIEL MEDINA  CENTRO 
87. ALEXANDRA PEREZ  SAN JOSE TEOCH (PENAL) 
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  

 
 
 
 
 
 
 
 
 
NOMBRES COLONIAS 
88. BERTHA MARTIN DELIO MORENO 
89. ARELY LARA  MERCEDES BARRERA  
90. ANGELICA  HACIENDA  
91. ADRIANA 
SANDORES  
DELIO MORENO 
92. BETY PALMA SERAPIO RENDON 
93. VENUS MONRROY VILLA MAGNA 
94. TRINI  DELIO MORENO  
95. MAYRA PEREZ  MELITON SALAZAR 
96. FRANCIA  SAN JOSE TEOCH 
97. HEIDI CANCHE  CENTRO 
98. LIZBET ZAPATA  MELITON SALAZAR 
99. EDWIN OXTE CASTILLA CAMARA 
100. LIZET NARVAEZ CASTILLA CAMARA 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  
 

 
 
 
 
 
 
NOMBRES COLONIAS 
101. ENRIQUE GARMA CENTRO 
102. BERENICE 
BLANCARTE 
FRACC DEL SUR 
103. MANUEL PECH DELIO MORENO (CEIBA) 
104. BERTHA VELEZ  OBRERA 
105. JEANINE ALONZO MERCEDES BARRERA 
106. CINTHIA CAAMAL DOLORES OTERO 
107. MARIA DEL 
SOCORRO 
CHUMINOPOLIS 
108. NORMA ROSSEL CENTRO 
109. MAYA PECH VILLA MAGNA 
110. SARA CANTO HERMITA  
 
 
 
 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  
 

 
 
 
 
 
 
 
NOMBRES COLONIAS 
111. GUADALUPE 
TRUJILLO 
MELITON SALAZAR 
112. FLOR TRUJILLO MELITON SALAZAR 
113. GABRIELA PERAZA CENTRO HERMITA 
114. MARISOL NARVAEZ  MANZANA 115 
115. GUADALUPE 
MELENDEZ 
CENTRO 
116. JESSICA PECH OBRERA 
117. MISHEO JIMENEZ  MELITON SALAZAR 
118. GUADALUPE ROSSEL  CENTRO 
119. MARTHA MARTIN  VILLA MAGNA  
120. MARIA CANTO CASTILLA CAMARA 
121. BEATRIZ AMPARO  VILLA MAGNA 
122. SIRENA  CASTILLA CAMARA 
123. MARIANA CAN CANTO 
RENTA DE LAVADORAS  
“LA BURBUJA FELIZ” 
 PARTICIPA EN LA RIFA! 
16 DE ENERO AL 13 DE FEBRERO  
 

 
 
 
 
 
 
 
 
 
NOMBRES  COLONIAS 
124. ROSITA  MANZANA 115 
125. GABRIELA AGUILAR MORELOS  
126. KARELY VIANA  CASTILLA CAMARA  
127. LUCY YAMA  SANTA ROSA  
128. ELDA PINTO CASTILLA CAMARA 
129. NAYELI BURGOS  MELITON SALAZAR 
130. VERONICA PEREIRA  SANTA ROSA  
`;

// Parsing logic
const participants = [];
const regex = /(\d+)\.\s+([\s\S]*?)(?=\n\d+\.\s+|$)/g;
let match;

while ((match = regex.exec(rawText)) !== null) {
  const fullText = match[2].trim();
  
  // Filtering out PDF headers/footers
  let cleanText = fullText.replace(/RENTA DE LAVADORAS[\s\S]*?FEBRERO/gi, '')
                          .replace(/N\s*OMB\s*RES\s*COLONIAS/gi, '')
                          .replace(/NOMBRES\s*COLONIAS/gi, '')
                          .trim();

  // Splitting lines
  const lines = cleanText.split('\n').map(l => l.trim()).filter(l => l && l.length > 0);
  
  let name = '';
  let colonia = '';

  if (lines.length === 1) {
    // Attempt to split by multiple spaces if only one line
    const parts = lines[0].split(/\s{2,}/);
    if (parts.length >= 2) {
        name = parts[0];
        colonia = parts.slice(1).join(' ');
    } else {
        name = lines[0];
        // Heuristic: Last 2-3 words might be colonia? Or just leave it empty.
        // Looking at data: "9. DAMARIS POOL CENTRO" -> Name: DAMARIS POOL, Colonia: CENTRO
        // "10. ISABEL EUAN VICENTE SOLIS" -> Name: ISABEL EUAN, Colonia: VICENTE SOLIS
        // "41. EVERLINDA AZCORRA" -> ??
        // Let's retry splitting by last reasonable chunk if it seems like a colonia
    }
  } else if (lines.length >= 2) {
    // If multi-line, usually first line(s) are name, last is colonia
    // "18. VERONICA \n MALDONADO \n MELITON SALAZAR"
    // "73. SELENE JIMENEZ \n DIAZ \n MERCEDES BARRERA"
    // "111. GUADALUPE \n TRUJILLO \n MELITON SALAZAR"
    
    // It seems the last line is almost always Colonia, and the rest is Name
    colonia = lines[lines.length - 1];
    name = lines.slice(0, lines.length - 1).join(' ');
  }

  // Refinement for single line cases manually if needed
  // "3. PILAR SANTA ROSA" -> Name: PILAR, Colonia: SANTA ROSA (maybe?)
  // Let's use a simpler heuristic for single lines: look for 2+ spaces separator
  if (lines.length === 1 && !colonia) {
      // If no double space found, try to assume last 1-2 words are colonia if the name is long enough
      // But many entries have "MERCEDES EUAN MELITON SALAZAR" with just single spaces?
      // Actually in the PDF text `1. MERCEDES EUAN  MELITON SALAZAR` has double space.
      // So the split(/\s{2,}/) should work.
      
      const parts = lines[0].split(/\s{2,}/);
       if (parts.length >= 2) {
        name = parts[0];
        colonia = parts.slice(1).join(' ');
       } else {
           // Fallback: If 3 or more words, take last 1 or 2 as Colonia?
           // This is risky. Let's just put everything in name and manually fix or leave it.
           // Or, look for known colonias?
           // "SANTA ROSA", "DOLORES OTERO", "VICENTE SOLIS", "ROBLE AGRICOLA"
           name = lines[0];
       }
  }

  participants.push({
    id: match[1],
    name: name,
    colonia: colonia
  });
}

console.log(JSON.stringify(participants, null, 2));
